### ISSUE TITLE
Better NumRetries implementation

### ISSUE THREAD

**Issue by jakepruitt** [mapbox/ecs-watchbot#106]
From #103:

> Write a better NumRetries implementation, which somehow only increments when the SQS message actually gets run by a worker.

Might have some tricky implementation details.

cc/ @rclark @emilymdubois

**Comment by rclark** [comment]
Here's a thought:

- We set up alarms for number of worker errors per minute
- We remove the NotifyAfterRetries parameter
- [Fix an issue here](https://github.com/mapbox/ecs-watchbot/blob/e7d41797367958875ce85136f83695835f395572/lib/messages.js#L130-L131): the 14-retry limit should only apply when expoential backoff is in effect, e.g. `return`, not `immediate`
- Add a dead letter queue, setup so that X retries on any job drops that job into the dead letter queue
- Setup alarms for messages landing in the dead letter queue

After all that: 
- you will be notified if your watchbot system is throwing errors at a high rate
- you will be notified if there is something wrong with a single job that keeps failing

I'm curious what some heavy watchbot users would think about this concept, which ties in closely with #76. It'd be a pretty dramatic shift in how you get notified about failed jobs.

cc @rodowi @l-r @jacquestardie

**Comment by mapsam** [comment]
Just wrapping my head around this concept, pardon if my questions aren't on track!

> dead letter queue

Is this a completely separate queue from watchbot's queue (i.e. `unpacker-production-WatchbotDeadLetter` queue)? If that queue becomes populated should the watchbot services have something built to ingest messages from that queue or should we just let them sit and remove them after investigation?

**Comment by rclark** [comment]
It is a separate queue. We may build some kind of manual utility to push them back at watchbot, but otherwise they would just sit there until they are investigated.

**Comment by rodowi** [comment]
👍  the dead letter queue would be a great addition to the stack

I'm concerned all the time about flooding the main queue with retrying jobs, and expiration rules make it difficult to track failed jobs (relying on cloudwatch metrics atm).

**Comment by mapsam** [comment]
Per discussion with @rclark, I'm 👍 to this concept. Flagging that since we plan to fail jobs if they cannot be allocated space, they'll have a hard-set retry limit before heading to the dead letter queue. This leaves open the chance that a perfectly fine task/message could fail to find adequate space in the cluster and would be put in the dead letter queue. We'll have to come up with some sort of mechanism (probably manual) that can relocate a dead letter queue task back into it's original watchbot queue. This should be clearly documented, as it could be very confusing if a valid task hits the queue.
