### ISSUE TITLE
Installing watchbot 4

### ISSUE THREAD

**Issue by jakepruitt** [mapbox/ecs-watchbot#202]
## Background

In order for users to run a watchbot 4 stack, they will need to install watchbot into their container’s environment in a way that exposes the `watchbot listen` command. This command will be the process run by the container at upstart to poll the queue, calling out to a subprocess with the user-provided command to process jobs.

The challenge is then figuring out how to install the `watchbot` command. While it’s probably easiest to use `npm install -g` `@``mapbox/watchbot`, we do not necessarily know if the container will have node/npm installed, or if that version of node/npm will be compatible with the async/await code inside of watchbot, which requires node version 8 or higher.

For that reason, we need to create an easier installation flow for users.

From @rclark in https://github.com/mapbox/ecs-watchbot/pull/184

> Since developers are going to need to "install" watchbot in their Dockerfiles, we should make that trivial, and it should bundle node v8 in a way that will allow watchbot to run independently of whatever node version the actual processing code requires.

## Ideal interface for installing watchbot 4

Here’s a rough sketch of how I imagine watchbot 4 could be installed in users’ Dockerfiles:

- When the Dockerfile is built, watchbot is downloaded via a `curl` command.
- The installation is done by a bash script, which sets up `watchbot` as an executable on the system, but does not override the default version of node.js on the system.
- After the Dockerfile is built and the user is ready to deploy the service, the cloudformation template created by `watchbot.template()` sets the `command` property in the task definition to be `command: 'watchbot listen <user-command>'`
- When `watchbot listen` is executed in the container, it implicitly uses node.js v8 to run `bin/watchbot.js`.
- When watchbot uses `child_process.spawn()` to create a worker, that worker has access to all of the environment packages set up in the Dockerfile, including whatever version of node.js the developer installed in the container, not the version installed by watchbot.

## Next actions

- Determine the URL where watchbot will be hosted. I imagine a github-based URL would be ideal here for open-source users.
- Write the bash script to install node.js version 8 in a place where it will not conflict with an already installed version of node.js. The installation script will also set the `watchbot` command up in the container’s `PATH` in a way that works on all linux operating systems.

cc/ @mapbox/platform-engine-room @emilymcafee

**Comment by jakepruitt** [comment]
> Watchbot is downloaded via a curl command.

Adding a **bonus challenge** here - how do we implement the installation with confidence that the URL contents won't be overridden? Should the URL come from a protected branch on github? How secure are github release versions?

cc/ @mapbox/security

**Comment by zmully** [comment]
This issue mirrors some discussions we've been having in security about bundling apps to reduce new employee install time. One package that @agius suggested looking at is [oclif-dev publish](https://github.com/oclif/dev-cli#oclif-dev-publish) which builds self-contained packages for Homebrew / macOS, Debian, Windows. While commandline oriented, we were looking at its bundling abilities. This could be run as part of the CI job, and published to a public location along with a bundle signature. I don't know how you'd prevent overwriting an existing package except with some pre bundling checks to see if a package with that gitsha/sig already exists. There may be a pattern here to copy from mason. 

GitHub releases don't bundle dependencies, so I think you're out of luck there.

**Comment by arunasank** [comment]
👋 @jakepruitt thanks for sketching this out! I agree with everything you've listed about an executable making the watchbot 3 to watchbot 4 migration easy for stacks that are not running on node 7.6+.

> Determine the URL where watchbot will be hosted. I imagine a github-based URL would be ideal here for open-source users.

We could also have an S3 url, to which something like npm-internal can help us push a pre-packaged bundle. We use public S3 urls for osm-qa-tiles already.

> Write the bash script to install node.js version 8 in a place where it will not conflict with an already installed version of node.js.
From https://nitayneeman.com/posts/standardizing-node.js-version-in-an-npm-package/, it seems like you can configure the nodejs version per package with the `--save-exact` flag. If this works, and we do this for ecs-watchbot, we may not have to worry about installing the secondary version of nodejs ourselves.

**Comment by jakepruitt** [comment]
Adding that we could use https://github.com/zeit/pkg to create a packaged binary (shout out to @rclark for the sweet find).

**Comment by arunasank** [comment]
I tested this today by:
* Packaging watchbot with https://github.com/zeit/pkg to generate watchbot binaries for windows, mac OS and Linux from the "♻️ that container" branch.
* The binaries are uploaded onto `https://s3.amazonaws.com/mapbox/watchbot/<os>/watchbot`, where <os> can be `windows`, `linux` or `macosx`. All the binaries have `public-read` access. 
* Testing it on a stack by using the pre-packaged binary instead of the npm installation, and it works!

## Usage
* Depending on the OS set up on the worker container, developers will have the option of using the linux, macosx or windows binaries. Recommended:
```
RUN wget --quiet https://s3.amazonaws.com/mapbox/watchbot/linux/watchbot -O /usr/local/bin/watchbot

RUN chmod +x /usr/local/bin/watchbot
```

for Linux for example.

## Maintaining watchbot binaries

We should not do this manually. Maybe we can set up a Lambda function that is triggered through a webhook that is triggered whenever there is a merge with the ecs-watchbot master, which generates fresh binaries and uploads them onto S3. But maybe we can ticket this and tackle it later with something like http://github.com/mapbox/patrol-rules-github.

**Comment by jakepruitt** [comment]
Nice @arunasank! 🎉 

## Questions:

1. Does this work on projects that don't have node.js installed?
2. Does this work for projects that have a different version of node.js installed?

## Maintaining

Do you think it'd be possible to use travis to do this build process? I know node-mapnik has a script that runs on `before_script` in their [`travis.yml`](https://github.com/mapnik/node-mapnik/blob/master/.travis.yml#L33-L36) that [parses the commit message to see if it's a merge commit](https://github.com/mapnik/node-mapnik/blob/master/scripts/publish.sh#L6) and runs the publishing process. This would save us one extra CI system.

**Comment by rclark** [comment]
Today I learned that CodeBuild projects can be triggered directly via github webhooks. This is worth some exploration -- the downside to using travis is that we'd have to give it permission to write the artifacts back to S3. I'd also be down to talk about how CodePipeline might be able to help here.

**Comment by arunasank** [comment]
> 1. Does this work on projects that don't have node.js installed?
> 2. Does this work for projects that have a different version of node.js installed?

Yes and yes! It's been tested with a node 8 stack, a node 2 stack and a bash stack. It works in all 3 cases.

> Today I learned that CodeBuild projects can be triggered directly via github webhooks. This is worth some exploration -- the downside to using travis is that we'd have to give it permission to write the artifacts back to S3. I'd also be down to talk about how CodePipeline might be able to help here.

Down to explore options here. Will keep you in the loop @rclark @jakepruitt

**Comment by arunasank** [comment]
Wanted to capture that locally node 7.6+ will still be required while deploying stacks, since requiring the `@mapbox/watchbot` module, in turn requires the `index.js` file, which exports certain libraries (like `lib/Messages.js`, for example) that use `async` `await`. Within each worker though, since the watchbot pinary is packaged, the scripts will have no strict requirement for a dependency on node 8.

**Comment by arunasank** [comment]
I found a small complication today, while migrating bench. The watchbot repository exposes two binaries:
* The watchbot.js file
* The [watchbot-log.js](https://github.com/mapbox/ecs-watchbot/blob/master/bin/watchbot-log.js) file.

The bench stack uses the second binary, which also depends on Node 8. In order to allow stacks that use the second binary to continue using it, we can do a couple of things:
* Generate two binaries - one for watchbot-log and watchbot, and allow users to wget the former only if they use it in their stack.
* Deprecate watchbot-log.js, since we have extensive logging in watchbot 4
* Integrate watchbot-log.js within watchbot.js, and trigger it with an argument other than "listen", like `watchbot log "<message>"`

I like solution 3 the best, since it unifies the binary and gives it multiple functions. Let me know if you all have opinions on the three options or other suggestions!
