### ISSUE TITLE
v4.20.0 binary on alpine causes segmentation fault

### ISSUE THREAD

**Issue by jakepruitt** [mapbox/ecs-watchbot#327]
Seeing that [ecs-telephone](https://github.com/mapbox/ecs-telephone/tree/420) with ecs-watchbot version 4.20.0 is failing with exit code `137` repeatedly:

<img width="1392" alt="Screen Shot 2019-12-19 at 5 27 43 PM" src="https://user-images.githubusercontent.com/5084263/71222339-0817e580-2285-11ea-94ce-602ed0bdf0f1.png">

We should dig into whether the issue is in the watchbot binary or in one of the dependencies. If we can't find the answer by the end of the year, we might want to roll back the 4.20 version.

**Comment by hcourt** [comment]
cc @aburkut 

When I originally published this I was able to get bench working in staging with the 4.20.0 version.  I'm curious what the difference is here, perhaps it is a dependency?

> essential container in task is exited

This exit code/message is pretty general and not super helpful, especially with no logs.  It points to the issue being with the docker configuration, I think, which is odd because I did not change the docker file in this version.

**Comment by hcourt** [comment]
More detail here: https://success.docker.com/article/what-causes-a-container-to-exit-with-code-137

**Comment by hcourt** [comment]
One thing that is suspicious to me about ecs-telephone is this line in the Dockerfile:
```
RUN apt-get update -qq && \
    apt-get install -y curl && \
    apt-get install -y wget && \
    curl -s https://s3.amazonaws.com/mapbox/apps/install-node/v2.0.0/run | NV=4.4.2 NP=linux-x64 OD=/usr/local sh && \
    apt-get autoremove -y
```
This is installing node version 4.4.2, which is probably not going to work.

**Comment by aburkut** [comment]
@jakepruitt @hcourt Another thing I'd like to mention is that deployment with ecs-watchbot@4.20 started to take much more time for [streets-review](https://github.com/mapbox/streets-review):

<img width="936" alt="streets-review — -bash — 173×39 2019-12-19 19-26-59" src="https://user-images.githubusercontent.com/2093810/71326328-32c6a000-250a-11ea-8433-a62b4b69f64f.png">

cc @mapbox/platform @mapbox/rave-tooling-sr

**Comment by aburkut** [comment]
@jakepruitt @hcourt Another thing I'd like to mention is that deployment with ecs-watchbot@4.20 started to take much more time.

**Comment by rclark** [comment]
It isn't clear to me what problem is being presented here. 

[@jakepruitt's logs](https://github.com/mapbox/ecs-watchbot/issues/327#issue-540686971) indicate that the watcher is running smoothly, but that child processes are being killed. That's the exit code 137 that's reported in logs -- watchbot running smoothly, child process being killed. This would indicate a problem that exists _entirely outside of ecs-watchbot itself_.

[@hcourt mentioned](https://github.com/mapbox/ecs-watchbot/issues/327#issuecomment-567988226)

> essential container in task is exited

... which is ECS speak for "the task stopped because a container stopped." It doesn't represent a problem as there are all kinds of legit reasons a container might stop. 

To add to the confusion, all ecs-watchbot containers exit with code 137. This is because the watchbot application is a non-stop loop. When ECS determines that the container needs to be stopped for any reason (e.g. service scaling, EC2 churn), it sends a SIGTERM. Watchbot ignores it and keeps looping. 30s later, ECS sends a SIGKILL and that results in container exit code 137.

Finally [@aburkut mentions launch times seeming to increase](https://github.com/mapbox/ecs-watchbot/issues/327#issuecomment-568393758). This is more likely due to runtime seg faults he was observing which have been reported elsewhere. He was able to avoid the problem by not using watchbot's pre-bundled binary, which is the prefered execution method for watchbot.

---

So short answer: there's a lot of confusion in this thread, but if there is actually an ecs-watchbot problem, it is a problem with the binaries that were built, and that's the direction we'd need to investigate.

@aburkut's seg faults were reported in a docker image `FROM node:12.13-alpine` so we should see if they can be reproduced and if we can determine if anything is wrong with our use of `pkg` to build these binaries.

Less important, ecs-watchbot's process should listen for `SIGTERM` and attempt to gracefully exit. This would allow watchbot containers to exit 0 when ECS asks it to shut down.

**Comment by rclark** [comment]
I can reproduce the problem with this dockerfile

```dockerfile
FROM node:12.13-alpine

RUN wget https://s3.amazonaws.com/watchbot-binaries/alpine/v4.20.0/watchbot -O /usr/local/bin/watchbot
RUN chmod +x /usr/local/bin/watchbot
```

After building this successfully, running the watchbot binary results in a seg fault:

```
❯ docker run -it watchbot-137-check sh
/ # watchbot
Segmentation fault
/ #
```

**Comment by rclark** [comment]
Seems related to https://github.com/zeit/pkg/issues/726. 

- Binaries for other OS (not alpine) work fine.
- I haven't been able to make the alpine binary work on a container with libstdc++ installed. This is the suggested workaround from the above issue.
- I can build a working alpine binary as long as I do the build on an alpine OS.

```dockerfile
FROM alpine:latest

WORKDIR /usr/local/src/watchbot
COPY ./ ./

RUN apk add git nodejs npm
RUN npm ci --production
RUN CODEBUILD_RESOLVED_SOURCE_VERSION=ca42944305fd75ef38017f0696a2b9f523c6767c node bin/watchbot-binary-generator.js
```
