### ISSUE TITLE
Proposal: InvocationError-like metric + alarm

### ISSUE THREAD

**Issue by yhahn** [mapbox/ecs-watchbot#76]
Thinking through the difference between how we alarm on watchbot vs lambda I'd like to try out a non per-job based error alarm approach.

Proposal:

- Put an error datapoint to CW per job that errors,
- Alarm on rates of errors rather than on individual jobs

This would mirror how our lambda invocation errors are handled and alarmed and prevent the 1:1 failed job to alarm ratio we have now (which can lead to 100s of alarms to go through and handle for what is often a single root cause).

cc @rclark @emilymcafee @emilymdubois

**Comment by rclark** [comment]
:+1: 

The flip-side situation is where there may be a required follow-up action for each failed job. In that case having the email record of everything can help. 

I can think of other ways to use watchbot's progress table that would help more, but we can tackle that separately. For now I think I'd like to see @yhahn's suggestion as default behavior with an opt-in to the current 1 alarm per failure method.

**Comment by l-r** [comment]
Another way to deal with this could be to use a [redrive policy](http://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/SQSDeadLetterQueue.html) on our SQS queue. By specifying a `maxReceiveCount` and `deadLetterTargetArn`, we'd create a second queue to hold the dead messages that could not be processed after X number of tries. This approach is nice because:

- it allows us to alarm on `ApproximateNumberOfMessages` of the dead letter queue
- it provides an easy way to capture and replay faulty input
- it reduces the CW put requests

**Comment by jakepruitt** [comment]
> Put an error datapoint to CW per job that errors,

This is now ready from #101. We just need to alarm on it. Will be the basis of a follow-up PR.

**Comment by rclark** [comment]
Closed in #114
