### ISSUE TITLE
NotifyAfterRetries doesn't work

### ISSUE THREAD

**Issue by rclark** [mapbox/ecs-watchbot#89]
[NotifyAfterRetries logic is applied in tasks.js](https://github.com/mapbox/ecs-watchbot/blob/9cc43e5f841e205f6775ea722b3c7878e1910d80/lib/tasks.js#L171), based on the presence of an environment variable set on  the *worker* container.

The problem is that this environment variable never gets set. Instead, [it is set on the *watcher* container](https://github.com/mapbox/ecs-watchbot/blob/9cc43e5f841e205f6775ea722b3c7878e1910d80/lib/template.js#L408).

I think the easiest approach to fixing this would be to set the value on the *worker* container as part of `lib/template.js`, as [part of the default set of variables provided in the `unpackEnv` function](https://github.com/mapbox/ecs-watchbot/blob/9cc43e5f841e205f6775ea722b3c7878e1910d80/lib/template.js#L713-L716). 

cc @mapsam

**Comment by mapsam** [comment]
@rclark what about taking advantage of the `options.env` parameter? This is also [added to the *worker* environment](https://github.com/mapbox/ecs-watchbot/blob/9cc43e5f841e205f6775ea722b3c7878e1910d80/lib/template.js#L711). Could we add the notifyAfterRetries value there instead? Otherwise we'll have to pass in the full *watcher* options object to the [`unpackEnv`](https://github.com/mapbox/ecs-watchbot/blob/9cc43e5f841e205f6775ea722b3c7878e1910d80/lib/template.js#L372) function just for notifyAfterRetries.

**Comment by rclark** [comment]
I would prefer if we could keep all the "default" env vars applied to the worker template in exactly the same way -- [the array here](https://github.com/mapbox/ecs-watchbot/blob/9cc43e5f841e205f6775ea722b3c7878e1910d80/lib/template.js#L713-L716) provides a really clear indication of what watchbot drops into the worker.

Maybe just pass the `options.notifyAfterRetries` value as a 3rd arg into the `unpackEnv` function?

**Comment by mapsam** [comment]
> really clear indication of what watchbot drops into the worker

Agreed - this feels like more explicit and readable route.

> 3rd arg into the unpackEnv function

Sounds good!

**Comment by mapsam** [comment]
Closed in #92 - good find @rclark
